import { CalendarEvent } from "@/types/calendar";

export const mockEvents: CalendarEvent[] = [
  {
    id: 1,
    title: "Audience tribunal",
    description: "Première audience pour le dossier Succession Martin",
    date: "2025-10-28",
    startTime: "09:00",
    endTime: "11:00",
    type: "hearing",
    priority: "high",
    location: "Tribunal de Grande Instance - Salle 3",
    caseId: 1,
    caseTitle: "Succession Martin",
    attendees: ["Me Sophie Durand", "M. Pierre Martin", "Mme Marie Martin"],
    color: "red",
  },
  {
    id: 2,
    title: "Échéance dépôt mémoire",
    description: "Date limite pour le dépôt du mémoire en défense",
    date: "2025-10-25",
    startTime: "17:00",
    endTime: "17:00",
    type: "deadline",
    priority: "high",
    caseId: 2,
    caseTitle: "Divorce Rousseau",
    color: "amber",
  },
  {
    id: 3,
    title: "Rendez-vous client",
    description: "Entretien initial avec nouveau client",
    date: "2025-10-24",
    startTime: "14:00",
    endTime: "15:30",
    type: "appointment",
    priority: "medium",
    location: "Cabinet - Bureau 2",
    attendees: ["M. Jean Dupont"],
    color: "blue",
  },
  {
    id: 4,
    title: "Réunion associés",
    description: "Point mensuel sur les dossiers en cours",
    date: "2025-10-26",
    startTime: "10:00",
    endTime: "12:00",
    type: "meeting",
    priority: "medium",
    location: "Salle de conférence",
    attendees: ["Me Sophie Durand", "Me Claire Bernard", "Me Antoine Petit"],
    color: "emerald",
  },
  {
    id: 5,
    title: "Médiation",
    description: "Session de médiation - Litige commercial",
    date: "2025-10-29",
    startTime: "14:00",
    endTime: "17:00",
    type: "meeting",
    priority: "high",
    location: "Centre de médiation",
    caseId: 3,
    caseTitle: "Litige immobilier Les Pins",
    attendees: ["Me Sophie Durand", "Médiateur", "Parties"],
    color: "primary",
  },
  {
    id: 6,
    title: "Signature acte",
    description: "Signature de l'acte de vente",
    date: "2025-10-30",
    startTime: "16:00",
    endTime: "17:00",
    type: "appointment",
    priority: "high",
    location: "Étude notariale",
    caseId: 4,
    caseTitle: "Vente propriété Marseille",
    color: "blue",
  },
  {
    id: 7,
    title: "Consultation juridique",
    description: "Conseil en droit du travail",
    date: "2025-10-31",
    startTime: "11:00",
    endTime: "12:00",
    type: "appointment",
    priority: "low",
    location: "Cabinet - Bureau 1",
    color: "zinc",
  },
  {
    id: 8,
    title: "Échéance appel",
    description: "Dernier jour pour faire appel",
    date: "2025-11-02",
    startTime: "23:59",
    endTime: "23:59",
    type: "deadline",
    priority: "high",
    caseId: 2,
    caseTitle: "Divorce Rousseau",
    color: "red",
  },
];
